### PR TITLE
shipStrawTracking: Move to argparse

### PR DESCRIPTION
**Pull request by olantwin**

### CODE REVIEW

**Review by fairlyons — CHANGES_REQUESTED** [review]
Works the same as before, "dummy" file is still created.

**Comment by olantwin** [comment]
> Works the same as before, "dummy" file is still created.

Changing the output behaviour (and fixing the write to the input file) is a matter for another PR.
A lot of cleanup needs to be done to the file.

**Comment by olantwin** [comment]
So if everything works as before, this PR works as intended.

**Review by fairlyons — APPROVED** [review]
I have tested and the functionality is unchanged.

**Pull request merged**
