### PR TITLE
Make line endings consistent (fix #360)

### LINKED ISSUE #360: Misconfigured line endings in `veto/veto.cxx` and `passive/ShipMuonShield.cxx`
Due to commits 8cd65a74c44a8587ec1ae2a38210de6a60a0f253 and 6fd2eabf78ba68df9380ac60ce316e65c0fc5a7f those two files are broken in my copy of the repository on lxplus, i.e. they show up as changed, but I can not check them out, stash them or do any other operations on them.

I remember that @evanherwijnen and Markus encountered this issue in the past. I'll have a look in the mailing list, whether I can reconstruct whether and how we fixed this in the past.

This is likely not an issue with the commits itself, but a symptom of misconfiguration of line-endings somewhere, resulting in git not being able to deal with this file...

Hints very much appreciated!

### PR DESCRIPTION
**Pull request by olantwin**
This change makes the line endings consistent throughout the repository. Combined with the .gitattributes setting we already adopted, this should fix the issue in most cases.

I don't think there's any way to avoid changing all line endings of the files affected. An alternative might be to do this change slowly file by file when they are touched (which will probably result in us forgetting to do this and this issue resurfacing with another file another time), or using git-filter to do it retroactively, which will change the git history for everyone, creating many other issues.

References: 
- https://stackoverflow.com/questions/1510798/trying-to-fix-line-endings-with-git-filter-branch-but-having-no-luck/4683783
- https://stackoverflow.com/questions/19488880/how-to-clean-up-line-endings-with-git
- https://stackoverflow.com/questions/18536863/git-refuses-to-reset-discard-files

### CODE REVIEW

**Comment by ThomasRuf** [comment]
~/.gitconfig 
[user]
	email = ...
	name =...
	password =...
[credential]
	helper = store

**Comment by olantwin** [comment]
Hm. Then I don't understand how this happened.

Is there anything in the `FairShip/.git/config`?

**Comment by ThomasRuf** [comment]
list of files with dos line endings. Still puzzled why it is an issue now. Many files were not changed for a long time.

ubuntu:/media/disk0/SHiPBuild/FairShip>find . -not -type d -exec file "{}" ";" | grep CRLF
./veto/veto.cxx: C++ source, ASCII text, with CRLF line terminators
./veto/veto.h: C++ source, ASCII text, with CRLF line terminators
./muonShieldOptimization/exitHadronAbsorber.h: C++ source, ASCII text, with CRLF line terminators
./muonShieldOptimization/simpleTarget.h: C++ source, ASCII text, with CRLF line terminators
./hcal/hcal.cxx: C++ source, ASCII text, with CRLF line terminators
./muon/muon.h: C++ source, ASCII text, with CRLF line terminators
./muon/muon.cxx: C++ source, ASCII text, with CRLF line terminators
./ecal/ecalCell.h: C++ source, ASCII text, with CRLF line terminators
./ecal/ecalDrawer.cxx: C++ source, ASCII text, with CRLF line terminators
./ecal/ecalCellMC.cxx: C++ source, ASCII text, with CRLF line terminators
./ecal/ecalDrawer.h: C++ source, ASCII text, with CRLF line terminators
./ecal/ecalCell.cxx: C++ source, ASCII text, with CRLF line terminators
./ecal/ecalCluster.cxx: C++ source, ASCII text, with CRLF line terminators
./ecal/ecalCellMC.h: C++ source, ASCII text, with CRLF line terminators
./passive/ShipMuonShield.h: C++ source, ASCII text, with CRLF line terminators
./passive/ShipMagnet.cxx: C source, ASCII text, with CRLF line terminators
./passive/ShipMuonShield.cxx: C source, ASCII text, with CRLF line terminators
./geometry/ecal_ellipse5x10m2.geo: ASCII text, with CRLF line terminators
./geometry/ecal_ellipse6x12m2.geo: ASCII text, with CRLF line terminators
./field/ShipBellField.h: C++ source, ASCII text, with CRLF line terminators
./field/ShipBellField.cxx: C++ source, ASCII text, with CRLF line terminators
./shipgen/MuDISGenerator.h: C++ source, ASCII text, with CRLF line terminators
./shipgen/MuDISGenerator.cxx: C++ source, ASCII text, with CRLF line terminators
./shipgen/CosmicsGenerator.h: C++ source, ASCII text, with CRLF line terminators
./shipgen/GenieGenerator.h: C++ source, ASCII text, with CRLF line terminators
./shipgen/NuageGenerator.h: C++ source, ASCII text, with CRLF line terminators

**Comment by olantwin** [comment]
I think the problem always occurs once they become mixed: as long as the files are untouched (or if git is instructed to keep them the way they were), it's unnoticeable...

**Comment by olantwin** [comment]
This is hopefully now obsolete with #367

**Pull request closed without merging**
