### PR TITLE
Truf/tunnelgeometry and muon dis

### PR DESCRIPTION
**Pull request by ThomasRuf**
Set of modifications for implementing TI8 tunnel and surroundings. Adapting muonDIS generator for new data format. Adding new ntuple (particle gun) generator for SND. Adding option to transport only muons via EmulsionDet.cxx, adding PreTrack method.

### CODE REVIEW

**Comment by olantwin** [comment]
Probably you meant to make the PR against sndsw?

**Comment by ThomasRuf** [comment]
what happened now?
I did clone, add my changes, did push. went to web interface started pull request. ???

**Comment by olantwin** [comment]
When making the pull request you have to select the correct repository.

The branch is fine. I can open a PR for you.

**Comment by olantwin** [comment]
This PR should probably be closed to avoid confusion.

**Comment by ThomasRuf** [comment]
why should it now be closed? Again confused.

**Comment by olantwin** [comment]
I expect you don't want to merge any of this into FairShip, right?

The correct PR is here: https://github.com/SND-LHC/sndsw/pull/39

**Comment by ThomasRuf** [comment]
so, i click here on Close with comment?

**Comment by olantwin** [comment]
Or just "close". Depending on whether you want to add a comment or not.

**Pull request closed without merging**
