### PR TITLE
Fix position of Pixel Volumes in geometry

### PR DESCRIPTION
**Pull request by owtscharenko**
Please excuse the second pull request today.
This one fixes the positions for the Volumes used for Simulation and the event display.

### CODE REVIEW

**Comment by ThomasRuf** [comment]
Hi,
It is difficult for me to find out what really has changed in charm-geometry_config.py, except of removing many blanks. 

regarding units, my I mention that shipunits.py exists. This should be used to make it obvious which units are used, and it provides automatic translation to standard FairShip units used internally, see many examples in geometry/geometry_config.py.

**Comment by owtscharenko** [comment]
Hi,

I changed the values for the single PixelModules.ySi() in lines 343, 347, 351 and so on. With the latest commit I used shipunit.py

**Comment by ThomasRuf** [comment]
OK. Is there any possibility that you can commit a file with only these changes?

**Comment by owtscharenko** [comment]
I removed the whitespace changes and updated my fork. Is this better?

**Comment by ThomasRuf** [comment]
yes, much better.

**Pull request merged**
