### PR TITLE
SND: allow disabling, disable by default

### PR DESCRIPTION
**Pull request by olantwin**
Following decision at physics meeting on 03/09/2024.

### CODE REVIEW

**Comment by olantwin** [comment]
Also includes slight refactoring of charmdet geometry loading, as I was touching those lines anyway. We should figure out whether there is any point in trying to maintain the charmdet code here (I think it's even outdated relative to the muonflux branch?) or just rip it out.

**Comment by fairlyons** [comment]
Many errors after exiting reconstruction:

Error in <TExMap::Remove>: key 93982891472168 not found at 30
Error in <TExMap::Remove>: key 93982891472568 not found at 24
Error in <TExMap::Remove>: key 93982891472768 not found at 21
Error in <TExMap::Remove>: key 93982891472968 not found at 20
Error in <TExMap::Remove>: key 93982891473168 not found at 17
Error in <TExMap::Remove>: key 93982891473512 not found at 59
Error in <TExMap::Remove>: key 93982891474144 not found at 84
Error in <TExMap::Remove>: key 93982891474344 not found at 82
Error in <TExMap::Remove>: key 93982891475432 not found at 59
Error in <TExMap::Remove>: key 93982891475776 not found at 1
Error in <TExMap::Remove>: key 93982891475976 not found at 1
Error in <TExMap::Remove>: key 93982891476176 not found at 1
Error in <TExMap::Remove>: key 93982891476952 not found at 64
Error in <TExMap::Remove>: key 93982891478360 not found at 59
Error in <TExMap::Remove>: key 93982891478976 not found at 69
Error in <TExMap::Remove>: key 93982891480056 not found at 37
Error in <TExMap::Remove>: key 93982891480824 not found at 1
Error in <TExMap::Remove>: key 93982891482088 not found at 49
Error in <TExMap::Remove>: key 93982891483496 not found at 44
Error in <TExMap::Remove>: key 93982891483984 not found at 30
Error in <TExMap::Remove>: key 93982891484184 not found at 24
Error in <TExMap::Remove>: key 93982891485272 not found at 1
Error in <TExMap::Remove>: key 93982891485760 not found at 85
Error in <TExMap::Remove>: key 93982891486104 not found at 25
Error in <TExMap::Remove>: key 93982891486304 not found at 24
Error in <TExMap::Remove>: key 93982891486504 not found at 21
Error in <TExMap::Remove>: key 93982891486704 not found at 20
Error in <TExMap::Remove>: key 93982891486904 not found at 17
Error in <TExMap::Remove>: key 93982891487104 not found at 15
Error in <TExMap::Remove>: key 93982891488352 not found at 51
Error in <TExMap::Remove>: key 93982891488960 not found at 54
Error in <TExMap::Remove>: key 93982891489304 not found at 94
Error in <TExMap::Remove>: key 93982891490392 not found at 71
Error in <TExMap::Remove>: key 93982891491048 not found at 20
Error in <TExMap::Remove>: key 93982891491248 not found at 18
Error in <TExMap::Remove>: key 93982891491592 not found at 59
Error in <TExMap::Remove>: key 93982891491936 not found at 1
Error in <TExMap::Remove>: key 93982891493088 not found at 40
Error in <TExMap::Remove>: key 93982891493488 not found at 36
Error in <TExMap::Remove>: key 93982891493864 not found at 9
Error in <TExMap::Remove>: key 93982891494208 not found at 49
Error in <TExMap::Remove>: key 93982891495136 not found at 69
Error in <TExMap::Remove>: key 93982891495384 not found at 13
Error in <TExMap::Remove>: key 93982891495584 not found at 13
Error in <TExMap::Remove>: key 93982891495784 not found at 9
Error in <TExMap::Remove>: key 93982891496128 not found at 50
Error in <TExMap::Remove>: key 93982891496472 not found at 91
Error in <TExMap::Remove>: key 93982891496904 not found at 18
Error in <TExMap::Remove>: key 93982891497112 not found at 24
Error in <TExMap::Remove>: key 93982891497320 not found at 30
Error in <TExMap::Remove>: key 93982891497528 not found at 36
Error in <TExMap::Remove>: key 93982891497728 not found at 36
Error in <TExMap::Remove>: key 93982891498272 not found at 75

Otherwise the geometry and reconstruction seem to work as intended.

**Comment by olantwin** [comment]
@antonioiuliano2 Could you please review?

#508 can be dealt with later, as it only happens on exit of the script, and doesn't affect any results.

**Review by antonioiuliano2 — APPROVED** [review]
Ok, I do not understand why the change in the shipcharm target configuration is also applied in this pull request. But I believe it all clear and well defined.

**Comment by olantwin** [comment]
> Ok, I do not understand why the change in the shipcharm target configuration is also applied in this pull request. But I believe it all clear and well defined.

I was modifying the lines anyway to make sure the indentation was consistent for the if/else, so I took the opportunity to do some very basic cleanup.

In general, we should discuss whether it's worth keeping the charmdet code around (I'm not sure whether it's even still up to date, as there's also the dedicated branch!)

**Pull request merged**
