### PR TITLE
Adjustable material frames around views for 2018 strawtubes geometry

### PR DESCRIPTION
**Pull request by DaniilSu**
They can be used with strawDesign=11 option

### CODE REVIEW

**Comment by ThomasRuf** [comment]
I would suggest to merge design 10 and 11. Design 10 was not yet used, and was meant to be the design for the 2018 geometry. Therefore, design 11 should become design 10.

if you change a header file, you need to increase the ClassDef number, otherwise ROOT will have problems to read old data: ClassDef(strawtubes,4) -> ClassDef(strawtubes,5)

did you run an overlap check? run_simScript with debug =2  # 2 make overlap check

**Comment by DaniilSu** [comment]
OK, I will make suggested changes. 
Yes, I performed the overlap check. I had to change floorHeightTankA to 3.0 m in order to avoid overlaps with decay volume.

**Comment by DaniilSu** [comment]
By the way during the overlap check I've found this strange overlap:

Info in <TGeoNodeMatrix::CheckOverlaps>: Checking overlaps for tTauNuDet and daughters within 0.0001
Check overlaps:      [==========]  119002 [100.00 %]           00:00           
Info in <TGeoNodeMatrix::CheckOverlaps>: Number of illegal overlaps/extrusions : 2

=== Overlaps for FAIRGeom ===
 = Overlap ov00000: tTauNuDet/volTauNuMudet_1 overlapping tTauNuDet/Pillar1Vol_1 ovlp=10
 = Overlap ov00001: tTauNuDet/volTauNuMudet_1 overlapping tTauNuDet/Pillar1Vol_2 ovlp=10

Is it normal?

**Comment by ThomasRuf** [comment]
no, it is not. i also saw it, and just informed Antonio.

**Pull request merged**
