### PR TITLE
Import TTCluster code by A. Petrov

### PR DESCRIPTION
**Pull request by olantwin**
As this code should be useful to FairShip and SNDSW, I suggest we merge it here and make SND-specific adjustments in SNDSW.

I am currently studying the code and Alex's presentation to understand what is implemented and what is left to do.

### CODE REVIEW

**Comment by ThomasRuf** [comment]
should it be placed in the nutaudet folder rather than in the python folder until the logic can be implemented in shipdigi and shipreco?

**Comment by olantwin** [comment]
Hm, I think generally it would be best to have all/most python modules in the python folder, so that imports etc. are straightforward, unless they are scripts which one would not want to import.

Also in light of SND@LHC, in which case this code would not be used for the nutaudet class.

**Comment by ThomasRuf** [comment]
yes, but this file is not yet ready to be imported anywhere. Does it produce digits? Are digits == cluster? Or are clusters ensemble of digits? How are the clusters saved to disk?

**Comment by olantwin** [comment]
> yes, but this file is not yet ready to be imported anywhere.

Maybe not yet, but I think there is little point in moving it back and forth.

> Does it produce digits? Are digits == cluster? Or are clusters ensemble of digits? 

The code generates clusters, but as part of this seems to simulate the light-yield per channel. I am still digging through the code, but I think it should be possible to also make these per-channel digitised hits available, without too much additional effort, as the information is internally available.

> How are the clusters saved to disk?

This is the responsibility of the code using the module. In the script there is a usage example, creating and plotting information from the

**Comment by olantwin** [comment]
For some additional information, [here the slides Alex shared with me](https://github.com/ShipSoft/FairShip/files/5994913/TT.in.FairShip.copy.pptx).

One thing I notice on slide 10 is that the substructure of the light yield isn't reproduced. I wonder whether this is an artifact of the readout via the SiPMs.

**Pull request merged**
