### PR TITLE
Remove charmdet and remnants of muflux

### PR DESCRIPTION
**Pull request by olantwin**
Last working (?) versions available for reference in `charmdet` and `muflux` branches respectively.

If there are no objections, this PR will be merged on Nov 4 after the software meeting. Silence will be interpreted as approval.

### CODE REVIEW

**Review by antonioiuliano2 — APPROVED** [review]
Hello, 
It is ok for me to remove the charmdet from the master branch.
(I would ask @evanherwijnen for confirmation on the muflux part).
Thanks,
Antonio

**Comment by olantwin** [comment]
> Hello, 
> It is ok for me to remove the charmdet from the master branch.
> (I would ask @evanherwijnen for confirmation on the muflux part).
> Thanks,
> Antonio

Thanks for the quick feedback!

**Comment by evanherwijnen** [comment]
Dear both
Does it do any harm to leave this branch in? The muflux branch contains stuff that may be re-usable.
Best wishes and cheers Eric
________________________________

**Comment by olantwin** [comment]
Dear Eric,

The branch will be kept indefinitely, and indeed, some things will likely provide valuable in future. The git history is also available as reference.

The change proposes only removing the remaining muon flux code from the master branch, as it is not completely up-to-date w.r.t the muflux branch, and adds to the work needed for testing and updating the code in the master branch.

Hope this clarifies the intentions of this change.

**Comment by evanherwijnen** [comment]
OK I understand, please go ahead, indeed I remember now that this branch was created.. cheers Eric
________________________________

**Comment by olantwin** [comment]
Merging, as approved by the code owners and testing didn't show any red flags (minor issue fixed in force-push).

**Pull request merged**
