### PR TITLE
simple exit without commiting suicide

### PR DESCRIPTION
**Pull request by siscia**
@olantwin Do you know why it was committing suicide before?

Is there some reason?

### CODE REVIEW

**Comment by olantwin** [comment]
@ThomasRuf  was having some issues with (my guess) destructors being called either in the wrong order or too many times, so that a clean exit would crash.

You should probably check with him whether this is still necessary.

If it's unnecessary (or we can find a better solution), I'd welcome that....

**Comment by siscia** [comment]
Let's wait for the CI and let's see! :)

**Comment by ThomasRuf** [comment]
Hi,
any python script which uses the Track class from GENFIT suffers from problems of exciting, for example ShipReco.py.

thomas

**Comment by siscia** [comment]
But do we remember what is the problem?

I am not seeing everything wrong in my local environment, still investigating the CI

**Comment by ThomasRuf** [comment]
This is the problem:

python -i $FAIRSHIP/macro/ShipReco.py -f ship.conical.Pythia8-TGeant4.root -g geofile_full.conical.Pythia8-TGeant4.root
...
finished writing tree
>>>  

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007fa791bc26c2 in __GI___waitpid (pid=91511, stat_loc=stat_loc
entry=0x7ffcac45e068, options=options
entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x00007fa791b2d067 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:149
#2  0x00007fa78e7c6133 in TUnixSystem::Exec (shellcmd=<optimized out>, this=0x55aeec0d6720) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/ROOT/v6-14-00-ship/0/core/unix/src/TUnixSystem.cxx:2119
#3  TUnixSystem::StackTrace (this=0x55aeec0d6720) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/ROOT/v6-14-00-ship/0/core/unix/src/TUnixSystem.cxx:2413
#4  0x00007fa78e7c8b24 in TUnixSystem::DispatchSignals (this=0x55aeec0d6720, sig=kSigSegmentationViolation) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/ROOT/v6-14-00-ship/0/core/unix/src/TUnixSystem.cxx:3644
#5  <signal handler called>
#6  0x00007fa760115029 in genfit::Track::Clear (this=this
entry=0x55af05bec180) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/FairShip/master/0/genfit/core/src/Track.cc:187
#7  0x00007fa76011510a in genfit::Track::~Track (this=0x55af05bec180, __in_chrg=<optimized out>) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/FairShip/master/0/genfit/core/src/Track.cc:173
#8  0x00007fa760115229 in genfit::Track::~Track (this=0x55af05bec180, __in_chrg=<optimized out>) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/FairShip/master/0/genfit/core/src/Track.cc:174
#9  0x00007fa78e7678e1 in TClass::Destructor (this=0x55aef9b445c0, obj=obj
entry=0x55af05bec180, dtorOnly=dtorOnly
entry=false) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/ROOT/v6-14-00-ship/0/core/meta/src/TClass.cxx:5152
#10 0x00007fa78e71af9e in R__ReleaseMemory (obj=0x55af05bec180, cl=<optimized out>) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/ROOT/v6-14-00-ship/0/core/cont/src/TClonesArray.cxx:143
#11 TClonesArray::~TClonesArray (this=0x55aef9b33510, __in_chrg=<optimized out>) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/ROOT/v6-14-00-ship/0/core/cont/src/TClonesArray.cxx:256
#12 0x00007fa78e71afd9 in TClonesArray::~TClonesArray (this=0x55aef9b33510, __in_chrg=<optimized out>) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/ROOT/v6-14-00-ship/0/core/cont/src/TClonesArray.cxx:264
#13 0x00007fa78e7678e1 in TClass::Destructor (this=0x55aef4960b20, obj=0x55aef9b33510, dtorOnly=<optimized out>) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/ROOT/v6-14-00-ship/0/core/meta/src/TClass.cxx:5152
#14 0x00007fa78fa13c37 in PyROOT::op_dealloc_nofree (pyobj=pyobj
entry=0x7fa76276bc50) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/ROOT/v6-14-00-ship/0/bindings/pyroot/src/ObjectProxy.cxx:59
#15 0x00007fa78fa13d69 in PyROOT::(anonymous namespace)::op_dealloc (pyobj=0x7fa76276bc50) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/ROOT/v6-14-00-ship/0/bindings/pyroot/src/ObjectProxy.cxx:212
#16 0x000055aeeb1b0702 in ?? ()
#17 0x000055aeeb163c4b in ?? ()
#18 0x000055aeeb199cfc in ?? ()
#19 0x000055aeeb1b5635 in _PyModule_Clear ()
#20 0x000055aeeb1b4bc0 in PyImport_Cleanup ()
#21 0x000055aeeb1b2088 in Py_Finalize ()
#22 0x000055aeeb14dc34 in Py_Main ()
#23 0x00007fa791affb97 in __libc_start_main (main=0x55aeeb14d6d0 <main>, argc=7, argv=0x7ffcac461108, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffcac4610f8) at ../csu/libc-start.c:310
#24 0x000055aeeb14d5ea in _start ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00007fa760115029 in genfit::Track::Clear (this=this
entry=0x55af05bec180) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/FairShip/master/0/genfit/core/src/Track.cc:187
#7  0x00007fa76011510a in genfit::Track::~Track (this=0x55af05bec180, __in_chrg=<optimized out>) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/FairShip/master/0/genfit/core/src/Track.cc:173
#8  0x00007fa760115229 in genfit::Track::~Track (this=0x55af05bec180, __in_chrg=<optimized out>) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/FairShip/master/0/genfit/core/src/Track.cc:174
#9  0x00007fa78e7678e1 in TClass::Destructor (this=0x55aef9b445c0, obj=obj
entry=0x55af05bec180, dtorOnly=dtorOnly
entry=false) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/ROOT/v6-14-00-ship/0/core/meta/src/TClass.cxx:5152
#10 0x00007fa78e71af9e in R__ReleaseMemory (obj=0x55af05bec180, cl=<optimized out>) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/ROOT/v6-14-00-ship/0/core/cont/src/TClonesArray.cxx:143
#11 TClonesArray::~TClonesArray (this=0x55aef9b33510, __in_chrg=<optimized out>) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/ROOT/v6-14-00-ship/0/core/cont/src/TClonesArray.cxx:256
#12 0x00007fa78e71afd9 in TClonesArray::~TClonesArray (this=0x55aef9b33510, __in_chrg=<optimized out>) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/ROOT/v6-14-00-ship/0/core/cont/src/TClonesArray.cxx:264
#13 0x00007fa78e7678e1 in TClass::Destructor (this=0x55aef4960b20, obj=0x55aef9b33510, dtorOnly=<optimized out>) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/ROOT/v6-14-00-ship/0/core/meta/src/TClass.cxx:5152
#14 0x00007fa78fa13c37 in PyROOT::op_dealloc_nofree (pyobj=pyobj
entry=0x7fa76276bc50) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/ROOT/v6-14-00-ship/0/bindings/pyroot/src/ObjectProxy.cxx:59
#15 0x00007fa78fa13d69 in PyROOT::(anonymous namespace)::op_dealloc (pyobj=0x7fa76276bc50) at /media/truf/disk2/home/truf/SHiPBuild/sw/SOURCES/ROOT/v6-14-00-ship/0/bindings/pyroot/src/ObjectProxy.cxx:212
#16 0x000055aeeb1b0702 in ?? ()
#17 0x000055aeeb163c4b in ?? ()
#18 0x000055aeeb199cfc in ?? ()
#19 0x000055aeeb1b5635 in _PyModule_Clear ()
#20 0x000055aeeb1b4bc0 in PyImport_Cleanup ()
#21 0x000055aeeb1b2088 in Py_Finalize ()
#22 0x000055aeeb14dc34 in Py_Main ()
#23 0x00007fa791affb97 in __libc_start_main (main=0x55aeeb14d6d0 <main>, argc=7, argv=0x7ffcac461108, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffcac4610f8) at ../csu/libc-start.c:310
#24 0x000055aeeb14d5ea in _start ()
===========================================================

**Comment by siscia** [comment]
I reached the same conclusion.

Overall the problem is here: https://github.com/ShipSoft/FairShip/blob/master/genfit/core/src/Track.cc#L187

I believe is some sort of double free, or free of something that is not been initialized.

If we want to try to fix this problem, I will suggest as first step to upgrade genfit to the latest version.

Then investigate it.

Or we can just ignore it and force the CI, or ignore the CI as well.

**Comment by olantwin** [comment]
If we decide to upgrade genfit, we should also use the opportunity to separate it from the repository to allow us to pick up bugfixes from upstream in future.

**Comment by ThomasRuf** [comment]
If we change the version of genfit, we would need a detailed study about how the result of the trackfit differs from the current version. This is mainly a serious problem for the muflux analysis. I would therefore suggest to postpone this issue until the muflux analysis is published. Except, if there is manpower available, and somebody can already start to test the performance with a recent genfit version now.

**Comment by siscia** [comment]
That's what I was worried about.

I will try to work around the issue for a couple of days next week.

**Comment by siscia** [comment]
The problem seems to be on this line here:

https://github.com/ShipSoft/FairShip/blob/7980826dc79d62d9ff75af212efa3fb2e01eb9fa/python/shipDigiReco.py#L929

**Comment by olantwin** [comment]
Coming back to this issue, as @shir994 also run into this now:

* Why does this exit have to happen for all scripts? Could this not be done only for scripts that need it, i.e. those that use genfit?
* Now that the muon flux studies are using a different branch anyway, we could reconsider updating/fixing genfit.

**Comment by ThomasRuf** [comment]
If anybody has any idea how to fix it, please go ahead.

**Comment by olantwin** [comment]
Would you agree that it is only needed for scripts using genfit? In that case, I would make a pull request to remove it from all other scripts, so that e.g. run_simScript.py exits normally.

**Comment by ThomasRuf** [comment]
How would you know that a script is using genfit?

**Comment by olantwin** [comment]
By checking whether the genfit module it used?

E.g. in `macro`, `ShipAna`, `ShipReco`, `MufluxReco` and `eventDisplay` seem to use `ROOT.genfit` (and some scripts in `macros/obsolete`).

Any cases you can think of where this would cause a false-negative for a python script?

**Comment by ThomasRuf** [comment]
you talk about scripts which are in fairship? What about private scripts?

**Comment by olantwin** [comment]
I don't think making all private scripts crash in a controlled manner seems particularly scalable either. (And already currently you need to import python/shipRoot_conf.py for the fix to work. If you use genfit in a private script without that, the identified issue also arises).

I think it's possible to check whether a certain module is loaded, but PyROOT's magic might interfere with that.

**Comment by ThomasRuf** [comment]
this should work:
for x in sys.modules: 
    if not x.find('genfit')<0: print x
... 
ROOT.genfit

**Comment by shir994** [comment]
I have applied the os kill fix in the #349 . Please, check if you are happy, @ThomasRuf @olantwin

**Comment by ThomasRuf** [comment]
outdated

**Comment by ThomasRuf** [comment]
outdated

**Pull request closed without merging**
