### PR TITLE
Update HNL production branching ratios & refactor Pythia configuration

### PR DESCRIPTION
**Pull request by Element-126**
_(This is a work in progress, please do net merge it yet)_

This PR updates the HNL production branching ratios, to match those in [arXiv: 1805.08567](http://arxiv.org/abs/1805.08567).

An earlier version of this branch was used for the PBC sensitivity curves.

Additionally, a number of bugs have been fixed, including some typos (wrong PDG ID / histogram name) as well as the secondary production from tau decays.

The code has been heavily refactored to make it simpler to *correctly* compute the branching ratios. However, it could certainly be simplified a bit more.

### CODE REVIEW

**Comment by Element-126** [comment]
Travis seems to be failing for an unrelated issue (the same for all PRs). Could someone knowledgeable about Travis have a look at it ?

Here is what seems to be the relevant part of the log:
```
[INFO   ] Monte Carlo Engine Initialisation with: TGeant4
input_line_302:1:10: fatal error: 'TG4GeometryServices.h' file not found
#include "TG4GeometryServices.h"
         ^
input_line_303:1:10: fatal error: 'TG4GeometryManager.h' file not found
#include "TG4GeometryManager.h"
         ^
Calling addVMCFields
Creating field map called MainSpecMap using /home/travis/build/ShipSoft/FairShip/files/MainSpectrometerField.root
ShipBFieldMap::readMapFile() creating field MainSpecMap using file /home/travis/build/ShipSoft/FairShip/files/MainSpectrometerField.root
x limits: -600.0000000, 600.0000000, dx = 10.0000000
y limits: -700.0000000, 700.0000000, dy = 10.0000000
z limits: -1000.0000000, 1000.0000000, dz = 10.0000000
Offsets: x = 0.0000000, y = 0.0000000, z = 3068.0000000
Angles : phi = 0.0000000, theta = 0.0000000, psi = 0.0000000
Total number of bins = 3429261; Nx = 121, Ny = 141, Nz = 201
Setting the Global field
Adding field MainSpecMap to Global
Traceback (most recent call last):
  File "../FairShip/macro/run_simScript.py", line 510, in <module>
    fieldMaker = geomGeant4.addVMCFields(ship_geo, '', True)
  File "/home/travis/build/ShipSoft/FairShip/python/geomGeant4.py", line 155, in addVMCFields
    geom = ROOT.TG4GeometryManager.Instance()
AttributeError: type object 'TG4GeometryManager' has no attribute 'Instance'
```

**Comment by olantwin** [comment]
Just ignore Travis. The build script does not work for the new way to install the SHiP software and I don't have the access rights to fix it.

I plan on replacing our CI over summer.

**Comment by ThomasRuf** [comment]
Forget about travis, not working, was never updated to use alibuild.

Von: Jean-Loup Tastet <notifications@github.com>
Gesendet: Mittwoch, 13. Juni 2018 16:28
An: ShipSoft/FairShip <FairShip@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [ShipSoft/FairShip] [WIP] Update HNL production branching ratios (#98)


Travis seems to be failing for an unrelated issue (the same for all PRs). Could someone knowledgeable about Travis have a look at it ?

Here is what seems to be the relevant part of the log:

[INFO   ] Monte Carlo Engine Initialisation with: TGeant4

input_line_302:1:10: fatal error: 'TG4GeometryServices.h' file not found

#include "TG4GeometryServices.h"

         ^

input_line_303:1:10: fatal error: 'TG4GeometryManager.h' file not found

#include "TG4GeometryManager.h"

         ^

Calling addVMCFields

Creating field map called MainSpecMap using /home/travis/build/ShipSoft/FairShip/files/MainSpectrometerField.root

ShipBFieldMap::readMapFile() creating field MainSpecMap using file /home/travis/build/ShipSoft/FairShip/files/MainSpectrometerField.root

x limits: -600.0000000, 600.0000000, dx = 10.0000000

y limits: -700.0000000, 700.0000000, dy = 10.0000000

z limits: -1000.0000000, 1000.0000000, dz = 10.0000000

Offsets: x = 0.0000000, y = 0.0000000, z = 3068.0000000

Angles : phi = 0.0000000, theta = 0.0000000, psi = 0.0000000

Total number of bins = 3429261; Nx = 121, Ny = 141, Nz = 201

Setting the Global field

Adding field MainSpecMap to Global

Traceback (most recent call last):

  File "../FairShip/macro/run_simScript.py", line 510, in <module>

    fieldMaker = geomGeant4.addVMCFields(ship_geo, '', True)

  File "/home/travis/build/ShipSoft/FairShip/python/geomGeant4.py", line 155, in addVMCFields

    geom = ROOT.TG4GeometryManager.Instance()

AttributeError: type object 'TG4GeometryManager' has no attribute 'Instance'

**Comment by Element-126** [comment]
Ok, I will ignore it

**Comment by Element-126** [comment]
BTW, what is the preferred way to include large data files ? The file `branchingratios.dat` weights 5.6MB, and I plan to nuke it in the future anyway (instead, the branching ratios will be computed on the fly).

One possibility would be to use Git LFS (but then all our users need to install this extension). Alternatively, we can leave this PR open until the file is not needed anymore. I will then `git rebase -i` it out of the history.

**Comment by olantwin** [comment]
I think option 2 (calculate on the fly and rebase) would be ideal, but to be honest we have several files much larger than that already in the repository (not that I'm happy with that, but now we just have to live with that...).

Now that CERN supports Git LFS, we should maybe consider using it.

**Comment by olantwin** [comment]
@FonsRademakers: Could you disable Travis please? You're the only one with the necessary access rights.

**Comment by ThomasRuf** [comment]
the place to store data is EOS, /eos/experiment/ship/data/ . Of course, it requires credentials, however the charm and beauty input files are also there, in any case needed for signal production.

**Comment by Element-126** [comment]
Let's go with option 2 then.

The branching ratios in this file have been computed with a standalone Python package which will probably be made public soon. If you wish (and have a GitLab account), I can give you access to its repository right now.

Until this is merged, if anyone needs to do simulations with HNLs, feel free to direct them to my fork. I regularly rebase it on master so it should always be reasonably up-to-date.

**Comment by ThomasRuf** [comment]
what is the time penalty for option 2, calculating on the fly? 
In fact, thinking more about it, if it is an ascii file, I would prefer to have it in git. That would enable to trace changes in the values. Otherwise, if it is calculated on the fly, how can I check what changed to previous version?

**Comment by Element-126** [comment]
Compared to the typical runtime of a typical FairShip simulation, computing the branching ratios on the fly should be roughly instantaneous (at the very least, much less than one second). Actually, it is probably faster than parsing the whole file.

**Comment by Element-126** [comment]
@ThomasRuf Regarding the tracing of changes versus the previous version, I was thinking of having some "physics regression tests", which could even be automated using Travis.

The idea is that we have ran a battery of validation tests to check that the new branching ratios actually make sense. Notably, we have compared them to a largely independent implementation (in Mathematica), and we have compared them to the tabulated PDG data for light neutrinos (when setting MN=0 and U2=[1,1,1]). This comparison to PDG data is partially automated, and is currently implemented in Jupyter notebooks (not in Python though...). So in principle, we could translate these notebooks into proper source files, and modify them to take the (improved) Pythia log file as input. This would allow us to re-run part of the validation after each commit. We could also compare the log file to the previous version for a fixed set of parameters, and raise an alert if anything changes.

This might actually be a superior solution, since it can also catch bugs happening between the calculation of the branching ratios and the Pythia configuration. There were actually a handful of them, either typos or related to the handling of coupling constants, so this would definitely be useful.

But this should be focus of another PR, and right now I cannot commit to do it in any reasonable time frame. But I keep this idea in mind

**Comment by olantwin** [comment]
@Element-126 I like the idea of these physics regression tests. I might contact you about them a little bit later this summer, when we have working CI again.

**Comment by Element-126** [comment]
BTW, here are for reference the validation plots for the comparison with PDG data.

The agreement is not perfect, but there are significant theoretical uncertainties (not plotted) due to the hadronic form factors.

validation_semileptonic_pseudoscalar
validation_semileptonic_vector
validation_tau_decays

**Comment by Element-126** [comment]
@olantwin Once I am done with my current paper, I can try to see how I can (locally) automate these tests.

**Comment by Element-126** [comment]
And here are the comparison plots with the previous branching ratios (BR_{FairShip} means the old branching ratios from FairShip, so what is plotted is actually Br(old)/Br(new)).

The labels are a bit messy but hopefully still understandable.

### Leptonic
ratio_leptonic

### Semileptonic (pseudoscalar)
ratio_semileptonic_pseudoscalar

### Semileptonic (vector)
ratio_semileptonic_vector

### Tau decays
ratio_tau_decays_logy

**Comment by Element-126** [comment]
Rebased on latest `master`

**Comment by ThomasRuf** [comment]
is there a plan to write a note which summarizes all this? It would be very helpful if in future publications we could refer to a public note describing the way production and decay of HNLs is being handled.

**Comment by Element-126** [comment]
The main reference, both for HNL production and decay, is:
* Bondarenko et al., _Phenomenology of GeV-scale Heavy Neutral Leptons_ ([arXiv: 1805.08567](http://arxiv.org/abs/1805.08567)).

For reference, the HNL decays have not been modified by this PR (except for the added possibility to specify different couplings for production and decay).

**Comment by ThomasRuf** [comment]
so, how do we proceed? Any further modifications in the pipeline? Should me merge it with the master?

**Comment by Element-126** [comment]
@ThomasRuf I will be busy on another project this week, but I plan to go back to this issue next week and get this code merged. The scalar portal code will probably be submitted around the same time.

If you are aware on anyone who needs to urgently run HNL simulations, please let me know.

**Comment by ThomasRuf** [comment]
May I ask where we are with the commit?

**Comment by Element-126** [comment]
Until now I was busy with another project, but I plan to get back to this very shortly (i.e. this week).

**Comment by Element-126** [comment]
Ok, I will now continue working on this PR until it is ready to be merged.

I have set up some basic regression tests (essentially an unordered diff of the Pythia setup log) to make sure that I don't break anything in the process.

**Comment by Element-126** [comment]
For now, I think I will include the data file in the PR, since I still cannot compute *all* the branching ratios on the fly (anything involving heavy baryons or Bc mesons is not implemented).

So I will just make some code clean-up and then squash all the commits.

**Comment by Element-126** [comment]
@ThomasRuf @olantwin 

I am roughly 1 day of work away from finishing this PR (including some unpushed changes). However, I currently cannot test my latest changes due to LXPLUS being excruciatingly slow (simply sourcing `config.sh` literally takes forever).

The easiest solution is probably to wait until LXPLUS is fully operational again. However, I would like to know what is the preferred way to locally install FairShip. Is there a specific distribution which is known to work ? (SLC6/7, Ubuntu ?) I have had a positive experience last year using Fedora, but this was with the old build procedure so things might have changed. And if I remember correctly, you were using some Ubuntu for the CI, so it probably used to work as well.

Many thanks in advance for your help! I will let you know when this is ready to be merged.

**Comment by ThomasRuf** [comment]
have a look at the instructions at https://github.com/ShipSoft/FairShip 

i installed fairship on virtual machines, openstack,  on different flavours of Ubuntu, latest 18.04, cc7, slc6, …
essential required to make git clone, and source the FairShip/aliBuild.sh. Eventually, some basic system libraries need to be installed. 


for ubuntu:

sudo apt-get update 
sudo apt-get install python-dev python-pip make patch sed git-all gedit environment-modules \
   libx11-dev libxpm-dev libxext-dev ncurses-dev libxml2-dev libxft-dev \
   libxmu-dev  ncurses-dev  curl bzip2  libbz2-dev gzip unzip tar gfortran libkrb5-dev \
    wget automake autoconf libtool bison  flex byacc libgif-dev libjpeg-dev libtiff5-dev\
   libexpat1-dev libcurl4-openssl-dev libssl-dev libbz2-dev libbz2-dev libglu1-mesa libglu1-mesa-dev\
   autopoint texinfo gettext libtool libtool-bin pkg-config python-tk cmake linuxbrew-wrapper krb5-user  dkms openafs-modules-dkms

sudo pip install --upgrade pip
sudo pip install matplotlib numpy scipy certifi ipython ipywidgets ipykernel notebook metakernel pyyaml sklearn

for kinit: cp from lxplus /etc/krb5.conf

**Comment by Element-126** [comment]
@ThomasRuf Thanks! I will try to install it in an Ubuntu 18.04 VM.

Do you have a rough estimate of the disk space needed for a full FairShip install ? This is to know how much disk space I should allocate.

**Comment by ThomasRuf** [comment]
to be safe, reserve 50GB. 30GB might also do it.

**Comment by olantwin** [comment]
@Element-126 Some added info from my side: You can count on the newest Fedora working, as that's what I develop on. Note: I install using `aliBuild` directly instead of `aliBuild.sh`, which works fine as well.

I also have CC7 docker images, which are automatically build on every commit to my master branch, but you can also use the `Dockerfile` in the repo to build other commits. All the dependencies are contained in the base layer, so it should take minutes at most. This might be good for testing your commits.

Finally, re disk size, my `sw` folder takes up 20GB, but the docker image is only about 5GB.

**Comment by Element-126** [comment]
@olantwin Thanks for the info! I think I will try with the Dockerfile, since my attempt at building FairShip on Ubuntu failed (when compiling ROOT 6).

But I will try that later. LXPLUS seems to be back, so I will first try to finish this PR. I have a regression to fix, some cleanup to do, and then more regression tests to carry out. If the stars align and LXPLUS keeps working, I should be done by tomorrow.

**Comment by ThomasRuf** [comment]
You probably have not enough memory to build root in parallel. Try alibuild with less CPUs.
Thomas



On Thu, Jul 12, 2018 at 1:13 PM +0200, "Jean-Loup Tastet" <notifications@github.com<mailto:notifications@github.com>> wrote:


@olantwin<https://github.com/olantwin> Thanks for the info! I think I will try with the Dockerfile, since my attempt at building FairShip on Ubuntu failed (when compiling ROOT 6).

But I will try that later. LXPLUS seems to be back, so I will first try to finish this PR. I have a regression to fix, some cleanup to do, and then more regression tests to carry out. If the stars align and LXPLUS keeps working, I should be done by tomorrow.

**Comment by Element-126** [comment]
@ThomasRuf You are indeed correct. The VM was completely OOM (even using basic shell commands failed with "cannot allocate memory"). I will retry with less threads and increase the RAM allocation from 4GB to 5-6GB.

**Comment by ThomasRuf** [comment]
Yes, it is completely crazy, but you need about 5-6GB per thread !!

Von: Jean-Loup Tastet <notifications@github.com>
Gesendet: Donnerstag, 12. Juli 2018 13:50
An: ShipSoft/FairShip <FairShip@noreply.github.com>
Cc: Thomas Ruf <Thomas.Ruf@cern.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [ShipSoft/FairShip] [WIP] Update HNL production branching ratios (#98)


@ThomasRuf<https://github.com/ThomasRuf> You are indeed correct. The VM was completely OOM (even using basic shell commands failed with "cannot allocate memory"). I will retry with less threads and increase the RAM allocation from 4GB to 5-6GB.

**Comment by Element-126** [comment]
I have fixed the regression (not pushed here yet) and more tests are currently running. So apart from some cleanup, I am almost done.

Before finalizing this PR, I had a rather general question regarding how I should approach development on FairShip.

Since I have mostly worked on HNLs so far, and I wanted to avoid unknowingly introducing regressions in the RPV SUSY code, some parts have necessarily diverged. So, in a few places, we end up with two different code paths doing essentially the same thing. This is certainly suboptimal. I will also have the same issue with the scalar portal code, since the original code which I and Kyrylo had to properly finish had been branched out of a ~6 month old version of FairShip, and was impossible to rebase since I only had the text files, not a full repository. So I decided to duplicate entire files to get the results in time for PBC without breaking anything else.

So I see at least two possible strategies, and I would like to know which one is preferred:
* Leave each model live in its own module, and let it diverge from the rest to avoid breaking it. This is not very elegant, but it should be quite foolproof. After all, there might be a good reason behind all the container hype today.
* Try to factor out as much code as possible, and use automated regression testing to check that the results remain the same. I have a script which does that by running the MC setup phase of the simulation for many different combinations of input parameters, and records all commands sent to Pythia. It can then display the diff between two FairShip revisions. This is very convenient when the results do match, but does not easily allow to locate the regression when things go wrong.

Which strategy do you think is the most reasonable here ? Any other ideas ?

**Comment by ThomasRuf** [comment]
I think similar reasons that you mention let to the current situation for the dark photon/RPV susy, which is unfortunate. Your second proposal would be the ideal solution.

**Comment by Element-126** [comment]
Ok, so I will try to factor things out for RPV SUSY. We'll see how it works

**Comment by Element-126** [comment]
@ThomasRuf I am currently trying to run regression tests for RPV SUSY (I did some minimally-intrusive changes but I would like to test them nonetheless). However, I am not very familiar with the model. Do you know what would be typical values for the neutralino mass, the stop mass and the production/decay couplings ? (I will need to run one test for each entry of a  "parameter matrix" covering all the relevant parameter space.) Maybe there is a SHiP note somewhere about this model.

Once I am done with that, I will rebase & squash and we should finally be able to merge this PR.

**Comment by Element-126** [comment]
@ThomasRuf I just noticed that when using the RPV SUSY model, the command line option `-A` is disregarded. Instead, production from charm is always used. Do you know if this is by design ? Otherwise I will fix it and run regression tests for charm only.

Here is the relevant line (`macro/run_simScript.py`):
```python
pythia8_conf.configurerpvsusy(P8gen,theMass,[theCouplings[0],theCouplings[1]],
                             theCouplings[2],RPVSUSYbench,'c',deepCopy)

```

**Comment by Element-126** [comment]
Ok, the regression tests pass for RPV SUSY.

I will now properly rearrange the commits, squash some of them, and try to write a small changelog.

I will take care of the scalar portal code later

**Comment by Element-126** [comment]
Rebased & squashed!

I will now re-run the regression tests for HNLs and RPV SUSY, and notify you when everything is ready to be merged.

Here is the changelog (copied from the commit message).

Changelog
=========

New features & logic bug fixes
------------------------------
* Implement leptonic, semileptonic (pseudoscalar & vector) and tau decay HNL
  production channels from 1805.08567.
* Properly implement secondary HNL production from tau decays (produced by Ds)
  * Fix the active-sterile couplings used for tau- -> nu_tau l- N.
    FairShip was incorrectly using U_tau^2, while for this class of processes
    it should use U_l^2 instead, since the HNL is produced at the same vertex
    as the outgoing charged lepton, not with the incoming tau.
  * Correctly handle the rescaling of tau branching ratios.
* Allow specifying different couplings for HNL production and decay.
  This is useful to build a sensitivity matrix.
* Separate HNL production through Bc meson decay (option -A bc).
  This avoids the issue of Bc decays being shadowed by B decays.
* Print the overall scaling factor used to optimize the event generation.
  This might eventually be useful to compute the absolute number of events.

Programming bug fixes
---------------------
* Make D+ decay to Kbar0 instead of K0.
* Fix wrong PDG ID for D_s+ in its decay channel list.
* Fix erroneous lepton ID in channel 'xic0_Xi-_mu'.
* Fix typo in histogram name 'tau__nu_e_bar_e'.
* Fix sign of PDG ID of outgoing tau neutrino in tau decay.
* Add missing 'idhadron' key to D_s+ -> eta l+ channels.

Refactoring
-----------
* Replace by-hand logging of Pythia setup by a systematic logging wrapper.
* Add dedicated function to make particles stable.
* Factor out the code needed to add HNLs to Pythia and ROOT.
* New parser for the branching ratio file, written in pure Python.
  * Does not depend on ROOT.
  * Stricter validation of input; includes additional sanity checks.
  * More flexible, should work well with variable mass discretization step.
  * Not significantly slower when compared to the typical total runtime.
* Use scipy.interpolate to extract the branching ratios.
  * More accurate that taking the lower neighbor.
  * Allows for arbitrary mass range and variable mass step (not implemented).
  * Allows for any kind of interpolation supported by scipy.interpolate.
  * Add utility function to reliably query the branching ratios (with correct coupling).
* Move particle and process data to a dedicated YAML file.
  * This provides better separation between logic and data.
  * Data is read into a dictionary.
  * There is no need to parse histogram names anymore (this was a source of bugs).
* Add some docstrings where useful.
* Factor out the setup code for B and Bc process selections.

Misc.
-----
* Ignore files generated when building FairShip.
* Fix misleading indentation caused by mixing tabs with spaces.
* Fix LaTeX descriptions for processes in `branchingratios.dat`.
* Use the future-proof `print` function.
* Many small fixes.

**Comment by Element-126** [comment]
This should now be ready for merging.

Let me know if you have comments / find any issue with the code.

On a side note, I attempted to handle secondary production in a more generic fashion. It did not work well enough to be used by default, and it added a lot of complexity, so I chose not to include this change here. But if in the future, the need arises to handle more complex decay chains, then let me know so we can avoid reinventing the square wheel :)

**Pull request merged**
