### PR TITLE
Update of the SND Muon Identification System geometry

### PR DESCRIPTION
**Pull request by dcentanni**
I improved the description of the Muon Identification System of the SND detector, I added the following components : 
- Upper Cover : an aluminum plate on the top of the detector;
- Lateral Cover : four aluminum covers attached to the lateral supports of the iron plates on both sides;
- Lateral Cross : two aluminum crosses on both sides standing between the Lateral Covers;
- Improved details of RPCs : aluminum frames, strips, gaps and gas.

Moreover, height and width of the iron plates and the lower/upper supports have been changed and the staggering of the RPC planes has been implemented.
The totality of these changes are made with respect to the following design by A. Crupano as shown by M. De Serio at the 19th SHiP collaboration meeting on 2nd of April 2020.
Schermata 2020-04-02 alle 13 46 14
perspective_total

### CODE REVIEW

**Comment by antonioiuliano2** [comment]
Hi Daniele,

I can currently see conflicts concerning the geometrical parameters files.

Probably you changed a parameter, which was already recently changed by someone else. The most probable conflict is with the new Upstream Veto Tagger class, which changed the same class attributes (NuTauMuDet) as you.

You should check these conflicts,
Antonio.

**Comment by olantwin** [comment]
@dcentanni If you're lucky, rebasing against master will take care of the conflicts.

**Comment by olantwin** [comment]
Those changes to `makeGenieEvents.py` and `run_simScript.py` seem unrelated and should not be part of this pull request.

**Comment by dcentanni** [comment]
> Those changes to `makeGenieEvents.py` and `run_simScript.py` seem unrelated and should not be part of this pull request.

I see it, it was not my intention, I was trying to fix it

**Comment by olantwin** [comment]
I would suggest doing the following (assuming you have `ShipSoft/FairShip` configured as remote `origin`):

```bash
git fetch origin/master
git rebase -i origin/master # make sure to drop the last two commits for makeGenieEvents.py, run_simScript.py
#... follow the instructions git gives you and fix any conflicts that emerge
# check everything is OK
git push --force # be careful! --force overwrites the remote repository
```

**Comment by dcentanni** [comment]
I think I managed to solve those conflicts

**Comment by olantwin** [comment]
In that case, only the spurious changes to unrelated files need to be removed.

Let's continue discussing via email.

**Pull request closed without merging**
