### PR TITLE
FairShip changes to make things easier for muflux and charm

### PR DESCRIPTION
**Pull request by evanherwijnen**
Extract all Muflux related things.

### CODE REVIEW

**Comment by ThomasRuf** [comment]
don't understand this part:
+  if charm==0: run.SetGenerator(primGen) 

because  charm == PG? If yes, I would suggest to remove  "run.SetGenerator(primGen)"  in if simEngine == "PG":

**Comment by ThomasRuf** [comment]
looking now at the full file, I think line 336 if charm==0: run.SetGenerator(primGen) should be removed. In any case, the primGen will be added to the run later on.

**Comment by evanherwijnen** [comment]
Hi Thomas
Charm is an integer, by default 0. Used for muflux and charm.
Cheers Eric

**Comment by ThomasRuf** [comment]
1.  Why it is not added when charm != 0?
  2.  In any case, same statement is executed some lines further down in the macro, now without if statement.

Von: eric van herwijnen <notifications@github.com>
Gesendet: Mittwoch, 30. Mai 2018 15:06
An: ShipSoft/FairShip <FairShip@noreply.github.com>
Cc: Thomas Ruf <Thomas.Ruf@cern.ch>; Comment <comment@noreply.github.com>
Betreff: Re: [ShipSoft/FairShip] FairShip changes to make things easier for muflux and charm (#93)

Hi Thomas
Charm is an integer, by default 0. Used for muflux and charm.
Cheers Eric

**Pull request merged**
