### PR TITLE
Truf/cavewithair

### PR DESCRIPTION
**Pull request by ThomasRuf**
cave.geo was using a mother volume filled with vacuum. Changed to caveWithAir.

### CODE REVIEW

**Comment by olantwin** [comment]
You probably wan't to make this pull-request relative to SND-LHC/sndsw

You can change the base branch when editing the pull request.

**Comment by ThomasRuf** [comment]
would have been too easy. so, i delete this request and start again?

**Comment by olantwin** [comment]
I think you can just edit this request.

**Comment by olantwin** [comment]
Or maybe not. I think you might have to close it and create a new pull request, sorry.

**Pull request closed without merging**
