### PR TITLE
Setting hole positions in MuonTagger as in July exposure

### PR DESCRIPTION
**Pull request by antonioiuliano2**
Hole positioning was lost after last commit, I merged it with the upgrade of MuonTagger geometry by Eric.

Best regards,
Antonio

bigger_walls

### CODE REVIEW

**Comment by ThomasRuf** [comment]
There are serious changes to the dimensions:

 old
    c.MuonTagger.BX = 195.3975 * u.cm 
    c.MuonTagger.BY = 121.7295 * u.cm 
new
    c.MuonTagger.BX = 2.40 *u.m 
    c.MuonTagger.BY = 2.20 * u.m 


 old
    c.MuonTagger.SX = c.MuonTagger.BX 
    c.MuonTagger.SY = c.MuonTagger.BY 
new
    c.MuonTagger.SX = 195.3975 * u.cm 
    c.MuonTagger.SY = 121.7295 * u.cm 


is this correct?

**Comment by olantwin** [comment]
This looks like one of the changes accidentally undone by Eric (see #151 for our original discussion).

**Comment by ThomasRuf** [comment]
so we have used in the meantime wrong dimensions?

**Comment by olantwin** [comment]
I think #158 undid the changes, so between then and whenever this is merged we have gone back to out of date RPC walls.

**Pull request merged**
