### PR TITLE
use ArgumentParser instead of getopt

### PR DESCRIPTION
**Pull request by ThomasRuf**
I started to replace getopt with ArgumentParser, which is much more user friendly. I started with run_simScript.py. There shouldn't be any change in the way of executing run_simScript.py. Please check and let me know if something does not work, which worked before. 

run_simScript.py --DarkPhoton does not work, but also didn't worked before the change.

### CODE REVIEW

**Comment by olantwin** [comment]
I am really happy about this change, as argumentparser is much easier to work with (and easier to debug etc.).

Two suggestions for improvement:

* In most cases, `dest=` does not need to be specified, as automatically the values will be stored in e.g. `--longoption`  → `options.longoption`.
* Instead of having dozens of default variables defined in the beginning, we can use the `default=` keyword argument to define the defaults, if they are not needed elsewhere in the file.

Happy to help with the transition of the other scripts and will have a more careful look if I notice anything in this script later.

**Comment by ThomasRuf** [comment]
for first point, if dest is specified, it cannot hurt. 
the second point, I don't understand.

**Comment by olantwin** [comment]
Some more comments:

* `required=` defaults to `False`. While it doesn't hurt to explicitly specify it, as we use many arguments, it distracts and reduces readability in my opinion.
* We could use the [`type`](https://docs.python.org/2/library/argparse.html#type) and [`choices`](https://docs.python.org/2/library/argparse.html#choices) keywords to perform simple validation of inputs, as we have several cases, where we expect e.g. a number or one of a certain list of choices.

**Comment by olantwin** [comment]
> for first point, if dest is specified, it cannot hurt.

While it can't hurt in the sense that the resulting behaviour is the same (or equivalent), I does think it reduces readability (but that's of course subjective)

> the second point, I don't understand.

Sorry, I noticed that in most cases where it does make sense (e.g. `nEvents`, `tankDesign`) the `default=` keyword is already in use.

**Pull request merged**
