### PR TITLE
Update shielding and hadron absorber

### PR DESCRIPTION
**Pull request by olantwin**

### CODE REVIEW

**Comment by ThomasRuf** [comment]
getting a core dump after this change:
...
Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100
target at -70.3225m 

 *** Break *** segmentation violation
Segmentation fault (core dumped)

#6  ShipMuonShield::ConstructGeometry (this=0x55f8a04e95c0) at /home/truf/FairShip/passive/ShipMuonShield.cxx:740
#7  0x00007fd95204dcea in FairMCApplication::ConstructGeometry (this=0x55f89cfb3610) at /SHiPBuild/sw/SOURCES/FairRoot/Oct17-ship/95c83579e1/base/sim/FairMCApplication.cxx:899
#8  0x00007fd9411085f8 in TG4RunManager::ConfigureRunManager (this=this
entry=0x55f8a51bd050) at /SHiPBuild/sw/SOURCES/GEANT4_VMC/v3-6-ship/e68f8e77a9/source/run/src/TG4RunManager.cxx:204
#9  0x00007fd9411094f2 in TG4RunManager::TG4RunManager (this=0x55f8a51bd050, runConfiguration=<optimized out>, argc=<optimized out>, argv=<optimized out>) at /SHiPBuild/sw/SOURCES/GEANT4_VMC/v3-6-ship/e68f8e77a9/source/run/src/TG4RunManager.cxx:128
#10 0x00007fd94110ad94 in TGeant4::TGeant4 (this=0x55f8a51a28e0, name=<optimized out>, title=<optimized out>, configuration=0x55f8a51d6290, argc=0, argv=0x0) at /SHiPBuild/sw/SOURCES/GEANT4_VMC/v3-6-ship/e68f8e77a9/source/run/src/TGeant4.cxx:229
#11 0x00007fd97afc8480 in ?? ()
#12 0x0000000000000000 in ?? ()

**Comment by olantwin** [comment]
Strange, which command line arguments did you run with? Maybe I missed a conditional/edge case somewhere.

**Comment by ThomasRuf** [comment]
Additional info run_simScript.py works. Problem is with using muonShieldOptimization/run_fixedTarget.py

**Comment by olantwin** [comment]
OK, I'll test and try to figure out why it doesn't work there. Is there a simple test command you can give me for `run_fixedTarget.py` that should work but doesn't? I don't think I ever ran it.

**Comment by ThomasRuf** [comment]
problem happens with design ds = 7, 
changing to 2016 geometry in run_simScript.py produces the same error. 

changing to design ds = 9 in run_fixedTarget causes a new problem:
#6  0x00007f9cf857c882 in exitHadronAbsorber::ConstructGeometry (this=0x555e29830250) at /home/truf/FairShip/muonShieldOptimization/exitHadronAbsorber.cxx:143

I guess, this is due to changing names. To place the sensitive plane after the hadron absorber, the following logic is used, probably now broken:
    TGeoVolume *muonShield = top->GetNode("MuonShieldArea_1")->GetVolume();
    Double_t z   = muonShield->GetNode("MagnAbsorb2_MagCRB_1")->GetMatrix()->GetTranslation()[2]; // this piece is bigger than AbsorberVol!
    TGeoBBox* tmp =  (TGeoBBox*)muonShield->GetNode("MagnAbsorb2_MagCRB_1")->GetVolume()->GetShape();
    Double_t dz  = tmp->GetDZ();
    zLoc = z+dz;
 

any suggestion how to fix it? Could ds =

**Comment by olantwin** [comment]
The problem for ds=9 is straight forward to fix. MagCRB does not exist anymore, as the sides of the magnets were straightened in #78 .

The other issue I'll investigate, I assume I missed a check for `fDesign == 7` somewhere.

**Comment by olantwin** [comment]
Should be fixed now in #101

**Pull request merged**
