### PR TITLE
Upstream Veto Tagger

### PR DESCRIPTION
**Pull request by CelsoFranco-dev**
Replacement of the Upstream Veto Tagger by the muRPC detector from LIP-Coimbra group

### CODE REVIEW

**Comment by antonioiuliano2** [comment]
Hi Celso,

thank you for your update. Could you please tell me what the new folder tmp you added represents? I cannot guess its purpose.

Best regards,
Antonio

**Comment by olantwin** [comment]
Hi Celso,
Your changes to `README.md` and `python/geomGeant4.py` undo recent changes to the master branch. Could you please remove those changes?

Why do you add `setUp.sh`?

Cheers,
Oliver

**Comment by ThomasRuf** [comment]
I think the tmp folder has to go, also setUp.sh.
It is not clear to me if Upstream Veto Tagger replaces an existing detector or is it optional? In the geometry config, existing parameters are just overwritten or commented, like
 #c.tauMudet.NmuRpc = 3
#c.tauMudet.deltay = 80* u.cm ...
as far as i can see, the digitize step is always done, even if detector does not exist?

why is kSTOPHERE changed to khSTOPHERE ?

**Comment by CelsoFranco-dev** [comment]
Dear all,

Yes, the tmp folder and setUp.sh are not needed and must be removed.
Regarding the files README.md and python/geomGeant4.py I dind't change
anything. If something is different we should recover the original files.

To my knowledge the Upstream Veto Tagger replaces the existing detector..
However, there might be a few leftovers of the previous detector. I'm sure
that Antonio will check this. If you prefer to have both options in
parallel it is also fine with me.

Right now the Upstream Veto Tagger consists of two layers of 5 muRPC
modules, with a transverse area large enough to cover the aperture of the
decay vessel. The final size of the modules has yet to be optimized. The
issue here is the particle rate on the extremities of the detector: these
RPCs can only handle 100 Hz/cm^2.s. Do you think this limit is safe? I
would like to perform a muon flux simulation to check this. Do you have
template scripts to submit this simulation in HTCondor?

Best regards,

Celso

Thomas Ruf <notifications@github.com> escreveu no dia quarta, 9/10/2019
à(s) 09:33:

**Comment by olantwin** [comment]
Hi Celso,
The changes to `README.md` and `python/geomGeant4.py` are probably due to old versions you had in your working directory.

I would highly suggest using `git` directly instead of using the web interface for anything but non-trivial changes to avoid issues like this.

Cheers,
Oliver

**Comment by ThomasRuf** [comment]
I haven't seen any update on the outstanding issues. How should we proceed?
cheers,
Thomas

**Comment by CelsoFranco-dev** [comment]
Dear Thomas,

You just need to pull the following files:

-  CMakeLists.txt, shipdata/ShipDetectorList.h,
geometry/geometry_config.py, geometry/media.geo,  python/shipDet_conf.py
and python/shipDigiReco.py

and folder:

-  UpstreamTagger

This detector replaces the 3 RPC layers that where inserted by Antonio at
the end of the muon detector. However, the detector to be replaced is not
completely removed from the constructor. As far as I can tell this is not a
problem but Antonio can check that quite easily. I'm traveling to CERN
tomorrow so we can discuss this at the collaboration meeting

Best regards,

Celso

Thomas Ruf <notifications@github.com> escreveu no dia segunda, 28/10/2019
à(s) 13:22:

**Comment by ThomasRuf** [comment]
Dear Celso,
I would rather prefer to have one pull request which I can merge or reject, rather than picking individual files myself.
best regards,
Thomas

**Comment by antonioiuliano2** [comment]
Dear Celso,

it is strongly recommended not to leave unpositioned volumes defined, since they spoil Geant indexing, as noticed in the message:

++++  TG4Warning:  ++++
    TG4SDServices::GetVolumeID:
    Unknown Volume Id for volRpc1
+++++++++++++++++++++++

I will be at CERN tomorrow too, so we can work on it there.

Best regards,
Antonio

**Comment by antonioiuliano2** [comment]
Dear Celso,

please check the pull request I opened to your branch:
https://github.com/CelsoFranco-dev/FairShip/pull/1

I have removed the calls to the RPC1 volume constructor, thus the message does not appear anymore.

**Comment by CelsoFranco-dev** [comment]
Dear Antonio,

Thanks a lot. I will delay the pull request for few days because I want to
optimize the transverse area of the detector. The final size will be
defined by the muon flux (I'm running the simulation right now).

Best regards,

Celso

Antonio <notifications@github.com> escreveu no dia terça, 29/10/2019 à(s)
16:17:

**Comment by antonioiuliano2** [comment]
Dear Celso,

how are you? I have checked the source of this conflict. It is due to this branch being out-date with FairShip/master. To solve the conflict, you should launch git merge with master branch, then edit the nutaudet/NuTauMudet.cxx, keeping our removal of the calls to RPC1 volume constructors.

If you have any question or encounter any problem, please let me know.

Best regards,
Antonio Iuliano

**Comment by CelsoFranco-dev** [comment]
Dear António,

Thanks for the help. I'm delaying the pull request of the Upstream Tagger
because I want to introduce some modifications that will minimize the time
uncertainty in case of multiple hits that are very apart in space. I'm also
running a muon flux simulation to check the charged particle rates. I will
submit a new pull request when ready.

Best regards,

Celso

Antonio <notifications@github.com> escreveu no dia terça, 19/11/2019 à(s)
10:33:

**Comment by ThomasRuf** [comment]
Can I close this request? Assume it is out of date.

**Comment by antonioiuliano2** [comment]
Dear Thomas,
I confirm that this pull request is out-of-date. When asking me to look at the new one (the one you have just merged), Celso explicitly wrote me to ignore the previous pull request. 

Therefore, I assume this should be closed without merge.

Best regards,
Antonio

**Pull request closed without merging**
