### PR TITLE
Fix bug with muontagger endpoints

### PR DESCRIPTION
**Pull request by evanherwijnen**

### CODE REVIEW

**Comment by ThomasRuf** [comment]
Don't understand. For horizontal strips, we need left and right end points, y left == y right, x left = - x right. For vertical strips, we need, x top == x bottom, y top = - y bottom. Or?

**Comment by evanherwijnen** [comment]
My fix takes also the width into account. The printout from drifttubeMonitoring/debugRPCstrips() is now correct.

**Comment by ThomasRuf** [comment]
I think the strips are not anymore vertical or horizontal, but inclined by width/length.

**Comment by evanherwijnen** [comment]
True. Can you please remove this pull request, I'll fix it.

**Pull request closed without merging**
