### PR TITLE
Autoformat files touched for new vessel

### PR DESCRIPTION
**Pull request by olantwin**
@anupama-reghunath Working on this branch, you can now check out files from your branches on top and use that to split your changes from the automatic ones.

### CODE REVIEW

**Comment by anupama-reghunath** [comment]
Should I merge this to the master? Or compare it otherwise?

**Comment by olantwin** [comment]
I wonder whether it's because I updated the clang-format config...

**Comment by olantwin** [comment]
Indeed, that should be the reason. 
I think it doesn't matter whether or not we merge this PR.
If you rebase off of it, it will be included in yours

**Comment by anupama-reghunath** [comment]
Ah, I end up getting some ugly merge conflicts when I try to rebase off of this.

**Comment by olantwin** [comment]
> Ah, I end up getting some ugly merge conflicts when I try to rebase off of this.

That's expected, see my message on mattermost.

**Comment by olantwin** [comment]
Now included in #468

**Pull request closed without merging**
