### PR TITLE
Fix #569: Use std::swap instead of TVectorD::Use()

### LINKED ISSUE #569: Issue with usage of ContstructedAt()
During testing of the usage of ConstructedAt() for MuonDIS ( In this case: `dPartDIS.ConstructedAt(nPart).Use(part)` ),  I found that while the code seems to work fine without any error, the TClonesArray() does not save the information onto the outputfile:

```
When writing:
DIS 0 mu+
DIS 1 pi-
DIS 2 gamma
DIS 3 gamma
DIS 4 proton
DIS 5 pi+
DIS 6 pi-
DIS 7 pi-
DIS 8 pi+
DIS 9 gamma
DIS 10 gamma

When reading:
 DIS Particle 0: PDG=0, Name=Rootino
 DIS Particle 1: PDG=0, Name=Rootino
 DIS Particle 2: PDG=0, Name=Rootino
 DIS Particle 3: PDG=0, Name=Rootino
 DIS Particle 4: PDG=0, Name=Rootino
 DIS Particle 5: PDG=0, Name=Rootino
 DIS Particle 6: PDG=0, Name=Rootino
 DIS Particle 7: PDG=0, Name=Rootino
 DIS Particle 8: PDG=0, Name=Rootino
 DIS Particle 9: PDG=0, Name=Rootino
 DIS Particle 10: PDG=0, Name=Rootino
```

This does not occur when using `dPartDIS[nPart]=part`

This issue was caused by commit b9309d0 : [Use ConstructedAt instead of remove pythonization for TClonesArray]

### PR DESCRIPTION
**Pull request by olantwin**
@antonioiuliano2 @anupama-reghunath Could you please confirm that this resolves the issue?

### CODE REVIEW

**Comment by antonioiuliano2** [comment]
Hello Oliver,
Thank you very much!

Indeed it solves the issue, but now I get empty muon array for odd event numbers (i.e. the events on neutrons):
```
Vector (11)  is as follows

     |        1  |
------------------
   0 |0 
   1 |0 
   2 |0 
   3 |0 
   4 |0 
   5 |0 
   6 |0 
   7 |0 
   8 |0 
   9 |0 
  10 |0.000262637
  ```
  
  Please let me check if I can replicate this issue and provide an example command

**Comment by olantwin** [comment]
Thanks Antonio, hopefully it's now fixed

**Comment by olantwin** [comment]
@antonioiuliano2 Could you please confirm that the fix worked or provide enough information that I can reproduce the issue?

**Comment by antonioiuliano2** [comment]
Thank you, I confirm it works

**Pull request merged**
